sudo: false

language: python

python:
  - 2.7
  - 3.6

install:
  - pip install codecov coverage

script:
  - |
    @PYTHON="$${PYTHON-python}"; export PYTHONPATH=test/test:lib; \
    echo "testing all (with $${PYTHON}) in test/test/test_*.py..."; \
    for i in test/test/test_*.py; do \
      COVERAGE_FILE=.coverage_$${i##*/} "$${PYTHON}" -m coverage run $${i}; \
    done; \
    "$${PYTHON}" -m coverage combine .coverage_*; \
    "$${PYTHON}" -m coverage report

after_success:
  - codecov
