sudo: false

language: python

python:
  - 2.7
  - 3.6

install:
  - pip install coverage

script:
  - python -c "import coverage"
  - echo $?
  - make travis

after_success:
  - bash <(curl -s https://codecov.io/bash)
